on: [ push ]

name: Linting & Checking

env:
  _CI_ONLY__DISABLE_DESMUME_SYS_BUILD_SCRIPT: "1"

jobs:
  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Clippy
        run: cargo clippy --release

  format-check:
    name: Rustfmt Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt
        run: cargo fmt --verbose -- --check
